[1] 
[2] # Copyright (C) Igor Sysoev
[3] # Copyright (C) Nginx, Inc.
[4] 
[5] 
[6] CFLAGS =	-q -O2 -tWM -w-8004 $(CPU_OPT)
[7] PCREFLAGS =	-DHAVE_CONFIG_H -DPCRE_STATIC -DPOSIX_MALLOC_THRESHOLD=10 \
[8] 		-DSUPPORT_PCRE8 -DHAVE_MEMMOVE
[9] 
[10] 
[11] pcre.lib:
[12] 	cd $(PCRE)
[13] 
[14] 	bcc32 -c $(CFLAGS) -I. $(PCREFLAGS) pcre_*.c
[15] 
[16] 	copy /y nul pcre.lst
[17] 	for %n in (*.obj) do @echo +%n ^^& >> pcre.lst
[18] 	echo + >> pcre.lst
[19] 
[20] 	tlib pcre.lib @pcre.lst
[21] 
[22] pcre.h:
[23] 	cd $(PCRE)
[24] 
[25] 	copy /y pcre.h.generic pcre.h
[26] 	copy /y config.h.generic config.h
[27] 	copy /y pcre_chartables.c.dist pcre_chartables.c
