[1] 
[2] # Copyright (C) Igor Sysoev
[3] # Copyright (C) Nginx, Inc.
[4] 
[5] 
[6] CFLAGS = -nologo -O2 -Ob1 -Oi -Gs $(LIBC) $(CPU_OPT)
[7] 
[8] zlib.lib:
[9] 	cd $(ZLIB)
[10] 
[11] 	cl -c $(CFLAGS) adler32.c crc32.c deflate.c \
[12] 		trees.c zutil.c compress.c \
[13] 		inflate.c inffast.c inftrees.c
[14] 
[15] 	link -lib -out:zlib.lib adler32.obj crc32.obj deflate.obj \
[16] 		trees.obj zutil.obj compress.obj \
[17] 		inflate.obj inffast.obj inftrees.obj
