[1] 
[2] # Copyright (C) Igor Sysoev
[3] # Copyright (C) Nginx, Inc.
[4] 
[5] 
[6] CFLAGS = -zq -bt=nt -ot -op -oi -oe -s -bm $(CPU_OPT)
[7] 
[8] zlib.lib:
[9] 	cd $(ZLIB)
[10] 
[11] 	wcl386 -c $(CFLAGS) adler32.c crc32.c deflate.c trees.c zutil.c &
[12] 		compress.c inflate.c inffast.c inftrees.c
[13] 	wlib -n zlib.lib adler32.obj crc32.obj deflate.obj trees.obj &
[14] 		zutil.obj compress.obj inflate.obj inffast.obj inftrees.obj
