[1] 
[2] # Copyright (C) Igor Sysoev
[3] # Copyright (C) Nginx, Inc.
[4] 
[5] 
[6] all:
[7] 	cd $(OPENSSL)
[8] 
[9] 	perl Configure BC-32 no-shared --prefix=openssl $(OPENSSL_OPT)
[10] 
[11] 	ms\do_nasm
[12] 
[13] 	$(MAKE) -f ms\bcb.mak
[14] 	$(MAKE) -f ms\bcb.mak install
[15] 
[16] 	# Borland's make does not expand "[ch]" in
[17] 	#    copy "inc32\openssl\*.[ch]" "openssl\include\openssl"
[18] 	copy inc32\openssl\*.h openssl\include\openssl
